import tsPlugin from "@typescript-eslint/eslint-plugin";
import tsParser from "@typescript-eslint/parser";
import importPlugin from "eslint-plugin-import";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import tsdocPlugin from "eslint-plugin-tsdoc";

// Mirrors carta-frontend's eslint.config.mjs, which is the house config.
// Three deliberate differences, each noted where it appears:
//
//   - The @blueprintjs plugin and its two rules are dropped: this project uses
//     Mantine, and the rules have nothing to check.
//   - The import-sort groups name this repo's own alias (@/...) rather than
//     CARTA's top-level folders.
//   - Two naming-convention selectors are relaxed for global consts. See the
//     comment on them.
export default [
    {
        // src/gen is generated by `npm run gen` and is not ours to lint.
        ignores: ["node_modules/**", "dist/**", "src/gen/**"]
    },
    {
        files: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
        languageOptions: {
            parser: tsParser,
            parserOptions: {
                ecmaVersion: "latest",
                sourceType: "module",
                project: ["./tsconfig.eslint.json"]
            }
        },
        plugins: {
            "@typescript-eslint": tsPlugin,
            import: importPlugin,
            "simple-import-sort": simpleImportSort,
            tsdoc: tsdocPlugin
        },
        rules: {
            "@typescript-eslint/naming-convention": [
                "error",
                {
                    selector: "default",
                    format: ["camelCase", "PascalCase", "UPPER_CASE"],
                    leadingUnderscore: "allow",
                    trailingUnderscore: "forbid"
                },
                {
                    selector: ["enumMember", "objectLiteralProperty", "typeProperty", "objectLiteralMethod", "typeMethod"],
                    format: null
                },
                {
                    selector: ["class", "enum", "interface", "typeAlias", "typeParameter"],
                    format: ["PascalCase"]
                },
                {
                    selector: "classProperty",
                    modifiers: ["public", "static", "readonly"],
                    format: ["UPPER_CASE"]
                },
                {
                    selector: "classProperty",
                    modifiers: ["private", "static", "readonly"],
                    format: ["PascalCase"]
                },
                {
                    selector: "classProperty",
                    modifiers: ["protected"],
                    format: ["camelCase"]
                },
                // Relaxed from the house config, which requires UPPER_CASE.
                // There it reads as "a global const is a constant"; here the
                // module-level consts are also the store, the client and the
                // slices, and Redux Toolkit names those in camelCase. Both are
                // allowed rather than renaming `store` to `STORE`.
                {
                    selector: "variable",
                    modifiers: ["const", "global"],
                    format: ["UPPER_CASE", "camelCase"]
                },
                // Relaxed for the same reason: in CARTA a global const function
                // is a React component and PascalCase is right. Here it is
                // often a selector or a thunk, so camelCase is allowed too.
                {
                    selector: "variable",
                    types: ["function"],
                    modifiers: ["const", "global"],
                    format: ["PascalCase", "camelCase"]
                },
                {
                    selector: ["function", "variable", "classProperty", "classMethod", "classicAccessor", "autoAccessor"],
                    format: ["camelCase"],
                    leadingUnderscore: "allow"
                },
                {
                    selector: ["parameter"],
                    format: ["camelCase", "PascalCase"],
                    leadingUnderscore: "allow"
                },
                {
                    selector: ["classicAccessor"],
                    modifiers: ["public", "static"],
                    format: ["PascalCase"]
                },
                {
                    selector: ["variable", "parameter", "classProperty", "classicAccessor", "autoAccessor"],
                    types: ["boolean"],
                    format: ["PascalCase"],
                    prefix: ["is", "are", "should", "has", "have", "can", "did", "will"],
                    leadingUnderscore: "allow"
                }
            ],
            "@typescript-eslint/no-deprecated": "error",
            "@typescript-eslint/no-unused-expressions": "error",
            "@typescript-eslint/consistent-type-imports": [
                "error",
                {
                    fixStyle: "inline-type-imports"
                }
            ],
            "no-unused-expressions": "off",
            "no-unused-vars": "off",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-unused-vars": [
                "error",
                {
                    args: "none"
                }
            ],
            "object-curly-spacing": "off",
            "simple-import-sort/imports": [
                "error",
                {
                    groups: [["^react", "^@?\\w"], ["^@/"], ["^\\u0000"], ["^\\.\\.(?!/?$)", "^\\.\\./?$"], ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"], ["^.+\\.?(css)$"]]
                }
            ],
            "simple-import-sort/exports": "error",
            "import/newline-after-import": "error",
            "import/no-duplicates": "error",
            "tsdoc/syntax": "error",
            "prefer-const": "error"
        }
    }
];
